name: Gridoria
options:
  bundleIdPrefix: com.mawelly
  deploymentTarget:
    iOS: "15.0"
packages:
  GoogleMobileAds:
    url: https://github.com/googleads/swift-package-manager-google-mobile-ads.git
    from: 11.0.0
targets:
  Gridoria:
    type: application
    platform: iOS
    deploymentTarget: "15.0"
    sources:
      - path: Gridoria
      - path: www
        buildPhase: resources
        type: folder
    dependencies:
      - package: GoogleMobileAds
    info:
      path: Gridoria/Info.plist
      properties:
        CFBundleDisplayName: Gridoria
        CFBundleIdentifier: com.mawelly.gridoria.JGF9X5ACM5
        CFBundleShortVersionString: "1.0.0"
        CFBundleVersion: "1"
        ITSAppUsesNonExemptEncryption: false
        CFBundleIcons:
          CFBundlePrimaryIcon:
            CFBundleIconFiles:
              - AppIcon
            CFBundleIconName: AppIcon
        CFBundleIcons~ipad:
          CFBundlePrimaryIcon:
            CFBundleIconFiles:
              - AppIcon
            CFBundleIconName: AppIcon
        UIRequiresFullScreen: true
        UILaunchStoryboardName: LaunchScreen
        UIViewControllerBasedStatusBarAppearance: true
        UIStatusBarHidden: true
        GADApplicationIdentifier: ca-app-pub-7719335438184188~4224547937
        NSUserTrackingUsageDescription: "Size daha alakalı reklamlar sunabilmek ve oyun deneyiminizi iyileştirmek için izninize ihtiyaç duyuyoruz."
        UIApplicationSceneManifest:
          UIApplicationSupportsMultipleScenes: false
          UISceneConfigurations:
            UIWindowSceneSessionRoleApplication:
              - UISceneConfigurationName: Default Configuration
                UISceneDelegateClassName: $(PRODUCT_MODULE_NAME).SceneDelegate
        CFBundleLocalizations:
          - tr
          - en
          - es
          - de
          - fr
          - pt
          - it
          - ru
        SKAdNetworkItems:
          - SKAdNetworkIdentifier: cstr6suwn9.skadnetwork
          - SKAdNetworkIdentifier: 4fzdc2evr5.skadnetwork
          - SKAdNetworkIdentifier: 2fnua5tdw4.skadnetwork
          - SKAdNetworkIdentifier: ydx93a7ass.skadnetwork
          - SKAdNetworkIdentifier: 5a6flpkh64.skadnetwork
          - SKAdNetworkIdentifier: p78axxw29g.skadnetwork
          - SKAdNetworkIdentifier: v72qych544.skadnetwork
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.mawelly.gridoria.JGF9X5ACM5
      DEVELOPMENT_TEAM: JGF9X5ACM5
      TARGETED_DEVICE_FAMILY: "1,2"
      SWIFT_VERSION: "5.0"
      ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
      INFOPLIST_FILE: Gridoria/Info.plist
      GENERATE_INFOPLIST_FILE: NO
